#!/bin/sh
# Author: Jens Getreu



package () {


OutDirName="$(dirname "$2")"
mkdir -p "$OutDirName"
ZipBaseName=$(basename "$2" ".zip")
ZipFileName="$OutDirName/$ZipBaseName.zip"
DownloadDir="./doc/build/html/_downloads/"
mkdir -p "$DownloadDir"



zip -r "$ZipFileName" "$1" 
cd "$DownloadDir"
ln -sf "../../../../$ZipFileName" .
}


package "bin/" "./doc/build/dist/asciidoctor-notetaking.zip"
